apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellynotifier
  namespace: jellynotifier
  labels:
    app: jellynotifier
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jellynotifier
  template:
    metadata:
      labels:
        app: jellynotifier
    spec:
      containers:
      - name: jellynotifier
        image: registry.germainleignel.com/personal/jellynotifier:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /webhook
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /webhook
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        env:
        - name: PORT
          value: "8080"
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000