apiVersion: v1
kind: Service
metadata:
  name: jellynotifier-service
  namespace: jellynotifier
  labels:
    app: jellynotifier
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: jellynotifier